### ISSUE TITLE
Test suite fails to run, unexpected token import

### ISSUE THREAD

**Issue by mspanish** [ktsn/svelte-jest#1] opened 2018-03-24 23:11 UTC
Hello thanks for this! I installed everything and can run jest but get errors - (I'm on Windows 10 with most recent npm and Node.js 9.4.0, Svelte 1.4.6

Error below.

```
 FAIL  src\collections.test.js
  ● Test suite failed to run

    C:\Users\mspan\Documents\aaaGitMine\aaSvelte\k\src\collections.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Collections from 'Collections.html';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.113s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by mspanish** [comment] 2018-03-24 23:53
One thing i can see is that your index.js and my index.js are very different - here is mine (I am using Rollup and its Svelte plugins to compile my app)

```
import App from "./App.html";

const app = new App({
  target: document.getElementById("root")
});

```

**Comment by ktsn** [comment] 2018-03-25 04:25
Hi, it seems like you are not include ES Module to CommonJS transform configuration. This is well known Jest pit fall which it does not handle ES Modules.

Try adding like the following babelrc (using `babel-preset-env`):

```js
{
  "presets": ["env"]
}
```

If you want to separate your app configuration from test enviroment, you can use `env` field:

```js
{
  "presets": [
     ["env", {"modules": false}]
  ],
  "env": {
    "test": {
      "presets:": ["env"]
    }
  }
}
```

**Comment by mspanish** [comment] 2018-03-26 09:39
Nope, still not working! Are the presets supposed to go in my package.json? I installed babel-preset-env via npm and changed my package.json so the relevant part looks like:

```
"presets": [
    "env"
  ],
  "jest": {
    "transform": {
      "\\.js$": "babel-jest",
      "\\.html$": "./src/index.js"
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "html"
    ]
  }
```

**Comment by ktsn** [comment] 2018-03-26 09:46
If you want to add it in `package.json`, you need to use `babel` field:

```js
{
  "babel": {
    "presets": ["env"]
  },
  "jest": {
    "transform": {
      "\\.js$": "babel-jest",
      "\\.html$": "svelte-jest"
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "html"
    ]
  }
}
```

FYI: https://babeljs.io/docs/usage/babelrc/#use-via-packagejson

**Comment by mspanish** [comment] 2018-03-26 18:28
I am using the babel field, and have all of the extensions installed - but I still get the same fail message. I am using Windows 10, if that makes any difference. I cloned your project locally and the jest tests do run fine there - but I see you are not using rollup, and your index compiles rather than references your App.html - it still seems that is the big difference in our 2 projects at this point.

**Comment by ktsn** [comment] 2018-03-26 19:04
Hmm, can you please share a minimal  reproduction as a fithub repo then? It will help us to solve the problem faster. 

I think the difference of OS seems not relevant here since the error is not such kind of one. Also the usage of rollup may be not relevant since it does not affect Jest behavior.

**Comment by mspanish** [comment] 2018-03-26 19:16
sure I can work on that - I'll make a smaller demo or my project and upload it for you - give me a little time ok!

**Comment by ktsn** [comment] 2019-08-19 06:40
Closing as not actionable currently. Please open a new issue if you can provide more info 🙂

**Closed by ktsn** 2019-08-19 06:40 UTC

**Comment by asm0dey** [comment] 2020-05-09 11:31
I have the same issue. What is the solution?
